### ISSUE TITLE
CFG: Ambiguity

### ISSUE THREAD

**Issue by Edraith** [PLMCSIT/Militari#1]
Paki-kumpleto yung CFG at pakifinalize.

**Comment by canaria10** [comment]
Progress CFG:
Global Declaration <✓>
Main <✓>
Printing and Scanning <✓>
Local Declaration: 
Local Declaration <✓>
Functions <✓>
Struct <✓>
Array Declaration <✓>
Body:
loops/Condition: <✓>
Condition <x>
Statements <✓>
There is no Condition statement in every loops.
