### ISSUE TITLE
CFG: Non-Terminal Condition is Missing.

### ISSUE THREAD

**Issue by canaria10** [PLMCSIT/Militari#2]
Code Sample:
`inorder(<condition>) {`
`<statement>`
`}`
`otherorder(<condition>){`
`<statement>`
`}`

> All Non-Terminal must have a sub terminals.
> I Think you Must put all possible format code for condition?
**What do you think?**

**Comment by Edraith** [comment]
pwede sige, try mo, keep us updated regarding dito sa Slack at dito sa Repo. Good Job bro!
