### ISSUE TITLE
Lexical Analyzer: Lexeme for Float var initialize value error

### ISSUE THREAD

**Issue by canaria10** [PLMCSIT/Militari#3]
The Lexeme value for the Float/Digit must be in this form:

> for Example:
> 1000.000.232
> Lexeme/`<Token>`:
> 1000.000 `<Valid>`
> 100.000.2 `<Invalid>`
> 32 `<Valid>``

**Comment by Edraith** [comment]
Please add the Code Snippet referring directly to this error output. Thanks!

**Comment by canaria10** [comment]
Progress: 50% out of 100% :)
